// <auto-generated />
using System;
using ControlPNP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SistemaControlPNP.Migrations
{
    [DbContext(typeof(ControlDBContext))]
    [Migration("20251117000532_Primera Migracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaControlPNP.Models.Asistencia", b =>
                {
                    b.Property<long>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAsistencia"));

                    b.Property<string>("Control_Asistencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("FechaIngreso");

                    b.HasIndex("FechaSalida");

                    b.HasIndex("IdPersonal");

                    b.HasIndex("IdPersonal", "FechaIngreso");

                    b.ToTable("Asistencia", null, t =>
                        {
                            t.HasCheckConstraint("CK_Asistencia_Orden", "([FechaSalida] IS NULL OR [FechaIngreso] <= [FechaSalida])");
                        });
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Auditoria", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InicioSesion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpUsuario")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RegistroID")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("Accion");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdUsuario", "FechaHora");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Movimiento", b =>
                {
                    b.Property<long>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMovimiento"));

                    b.Property<string>("Autoriza")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaRetorno")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Novedades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("FechaRetorno");

                    b.HasIndex("FechaSalida");

                    b.HasIndex("IdPersonal");

                    b.ToTable("Movimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Mov_OrdenHoras", "([FechaRetorno] IS NULL OR [FechaSalida] <= [FechaRetorno])");
                        });
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Personal", b =>
                {
                    b.Property<int>("IdPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonal"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Foto")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Grado")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("Huella")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroCip")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(1)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdPersonal");

                    b.HasIndex("Apellidos");

                    b.HasIndex("CorreoInstitucional");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroCip")
                        .IsUnique();

                    b.ToTable("Personal", null, t =>
                        {
                            t.HasCheckConstraint("CK_Personal_CIP_Exact8Digits", "LEN([NumeroCip]) = 8 AND [NumeroCip] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Personal_DNI_Exact8Digits", "LEN([Dni]) = 8 AND [Dni] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Personal_FechaNacimiento_Rango", "[FechaNacimiento] >= '1900-01-01' AND [FechaNacimiento] <= CAST(SYSUTCDATETIME() AS date)");

                            t.HasCheckConstraint("CK_Personal_Sexo", "[Sexo] IN ('M','F')");
                        });

                    b.HasData(
                        new
                        {
                            IdPersonal = 1,
                            Apellidos = "PEREZ GARCIA",
                            CorreoInstitucional = "juan.perez@policia.gob.pe",
                            Direccion = "Av. Los Olivos 123",
                            Dni = "87654321",
                            Estado = true,
                            FechaNacimiento = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Grado = "CAP. PNP",
                            Nombres = "JUAN",
                            NumeroCip = "12345678",
                            Sexo = "M",
                            Telefono = "999888777",
                            Unidad = "DIRINCRI"
                        });
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersonal");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Asistencia", b =>
                {
                    b.HasOne("SistemaControlPNP.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Auditoria", b =>
                {
                    b.HasOne("SistemaControlPNP.Models.Usuario", "UsuarioRef")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Auditoria_Usuarios");

                    b.Navigation("UsuarioRef");
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Movimiento", b =>
                {
                    b.HasOne("SistemaControlPNP.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("SistemaControlPNP.Models.Usuario", b =>
                {
                    b.HasOne("SistemaControlPNP.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
